spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8761

eureka:
  server:
    wait-time-in-ms-sync-empty: 0
  client:
    fetch-registry: false
    register-with-eureka: false
